
parameters:
    script_service_parameters:
        template: "AppBundle:Script:template.js.twig"
        dir:      "%kernel.root_dir%/../web/script"
        file:     "generated-script.js"

    script_image_service_parameters:
        temp_dir:  "%kernel.root_dir%/../web/script/temp"

services:
    config_service:
        class: AppBundle\Services\ConfigService
        arguments: [ "@snc_redis.default" ]

    config_validator_service:
        class: AppBundle\Services\ConfigValidatorService
        arguments: [ "@script_image_service" ]

    script_image_service:
        class: AppBundle\Services\ScriptImageService
        arguments: [ "%script_image_service_parameters%" ]

    script_service:
        class: AppBundle\Services\ScriptService
        arguments: [ "%script_service_parameters%", "@templating", "@config_service", "@script_image_service" ]
