
parameters:
    modal_script_dir: "%kernel.root_dir%/../web/modal-script"
    modal_script_template: "AppBundle:ModalScript:page.html.twig"

services:
    config_service:
        class: AppBundle\Services\ConfigService
        arguments: [ "@snc_redis.default" ]

    config_validator_service:
        class: AppBundle\Services\ConfigValidatorService

    modal_script_service:
        class: AppBundle\Services\ModalScriptService
        arguments: [ "@config_service", "@templating", "%modal_script_dir%", "%modal_script_template%" ]