
parameters:
    script_dir: "%kernel.root_dir%/../web/modal-script"
    script_template: "AppBundle:ModalScript:page.html.twig"

services:
    config_service:
        class: AppBundle\Services\ConfigService
        arguments: [ "@snc_redis.default", "@image_service" ]

    config_validator_service:
        class: AppBundle\Services\ConfigValidatorService
        arguments: [ "@image_service" ]

    image_service:
        class: AppBundle\Services\ImageService

    script_service:
        class: AppBundle\Services\ScriptService
        arguments: [ "@config_service", "@templating", "%script_dir%", "%script_template%" ]